/**
 * Core shared types for the chat component and its transports.
 */

export type Role = 'system' | 'user' | 'assistant';

export interface ChatMessage {
  /** Stable unique id. Generated by the component if not supplied. */
  id: string;
  role: Role;
  content: string;
  /** Epoch ms. */
  createdAt: number;
  /** True while the assistant message is still streaming in. */
  streaming?: boolean;
  /** Set when generation failed for this message. */
  error?: string;
}

/**
 * A single chunk yielded by a transport while streaming a response.
 *
 * - `delta`: append this text to the assistant message.
 * - `done`:  the stream has finished cleanly.
 * - `error`: the stream failed; `error` holds a human-readable message.
 */
export type StreamChunk =
  | { type: 'delta'; delta: string }
  | { type: 'done' }
  | { type: 'error'; error: string };

/**
 * The pluggable transport interface. Anything that can turn a list of messages
 * into an async stream of chunks is a valid transport. Built-in adapters
 * (OpenAI-compatible, Anthropic) implement this, and users can bring their own.
 */
export interface ChatTransport {
  /**
   * Send the conversation and stream back the assistant's reply.
   *
   * @param messages  Full conversation so far (including the latest user turn).
   * @param signal    Aborted when the user hits "stop" or the element unmounts.
   */
  send(
    messages: ChatMessage[],
    signal: AbortSignal,
  ): AsyncIterable<StreamChunk>;
}
