/**
 * Core shared types for the chat component and its transports.
 */

export type Role = 'system' | 'user' | 'assistant';

/**
 * Why the model stopped generating, normalized across providers so a consumer
 * writes one check regardless of which backend produced it. The provider's
 * original string is preserved separately (see `rawFinishReason`).
 *
 * - `stop`:           finished naturally (OpenAI `stop`, Anthropic `end_turn`/`stop_sequence`).
 * - `length`:         truncated at the token limit (OpenAI `length`, Anthropic `max_tokens`).
 * - `content_filter`: blocked by a safety filter (OpenAI `content_filter`, Anthropic `refusal`).
 * - `tool_calls`:     stopped to call a tool (OpenAI `tool_calls`, Anthropic `tool_use`).
 * - `other`:          any reason the adapter didn't recognize.
 */
export type FinishReason =
  | 'stop'
  | 'length'
  | 'content_filter'
  | 'tool_calls'
  | 'other';

/**
 * Token counts for a completed turn, when the provider reports them. Either
 * field may be absent if the provider (or a compatible server, e.g. some Ollama
 * builds) doesn't send it.
 */
export interface TokenUsage {
  /** Prompt/input tokens billed for this turn. */
  inputTokens?: number;
  /** Completion/output tokens generated. */
  outputTokens?: number;
}

/**
 * A file or image attached to a message. The component creates these from a
 * local pick / drag-drop / paste; a consumer can also construct them when
 * rehydrating a conversation from storage.
 *
 * Only `kind: 'image'` attachments are sent to the built-in OpenAI/Anthropic
 * adapters (those streaming chat APIs accept images directly). Other files still
 * render in the UI and reach the consumer via `ai-chat:submit`, so a consumer
 * with their own backend can handle them.
 */
export interface Attachment {
  /** Stable unique id. Generated by the component for local picks. */
  id: string;
  /**
   * `'image'` renders inline and is sent to image-capable adapters; `'file'`
   * renders as a chip and is surfaced to the consumer but not auto-sent.
   */
  kind: 'image' | 'file';
  /** MIME type, e.g. `'image/png'`, `'application/pdf'`. */
  mimeType: string;
  /** Original (or synthesized, for pasted images) filename, for display. */
  name: string;
  /** Byte size, for display and limit enforcement. */
  size: number;
  /**
   * A URL the component can render immediately: a `data:` URL the component
   * generated from the file (default), or an `https:` URL a consumer swapped in
   * after uploading to storage. This is also what image-capable adapters send.
   */
  url: string;
  /**
   * The raw `File`, when the component created this from a local pick/drop/paste.
   * Absent after a consumer reconstructs a message from storage. Lets a consumer
   * upload the bytes without re-reading them.
   */
  file?: File;
  /** A second line under a file's name on its card, e.g. "Excel · 42 rows". */
  detail?: string;
  /**
   * The app is still making this file: its card reads the `preparingFile` label
   * and cannot be opened until you clear it.
   */
  busy?: boolean;
}

export interface ChatMessage {
  /** Stable unique id. Generated by the component if not supplied. */
  id: string;
  role: Role;
  content: string;
  /**
   * Files/images attached to this message. Optional and additive — a message
   * without attachments behaves exactly as before. Only image attachments are
   * sent to the built-in adapters (see {@link Attachment}).
   */
  attachments?: Attachment[];
  /** Epoch ms. */
  createdAt: number;
  /** True while the assistant message is still streaming in. */
  streaming?: boolean;
  /** Set when generation failed for this message. */
  error?: string;
  /**
   * Why generation stopped, normalized across providers. Present on a settled
   * assistant turn when the transport reported it. `length` means the reply was
   * cut off at the token limit.
   */
  finishReason?: FinishReason;
  /** Token counts for this turn, when the provider reports them. */
  usage?: TokenUsage;
}

/**
 * A single chunk yielded by a transport while streaming a response.
 *
 * - `delta`: append this text to the assistant message.
 * - `done`:  the stream has finished cleanly. May carry `finishReason` and
 *            `usage` metadata when the provider reports them.
 * - `error`: the stream failed; `error` holds a human-readable message.
 */
export type StreamChunk =
  | { type: 'delta'; delta: string }
  | {
      type: 'done';
      /** Normalized stop reason, when the provider reported one. */
      finishReason?: FinishReason;
      /** The provider's original stop-reason string, unmodified. */
      rawFinishReason?: string;
      /** Token counts, when the provider reported them. */
      usage?: TokenUsage;
    }
  | { type: 'error'; error: string };

/**
 * The pluggable transport interface. Anything that can turn a list of messages
 * into an async stream of chunks is a valid transport. Built-in adapters
 * (OpenAI-compatible, Anthropic) implement this, and users can bring their own.
 */
export interface ChatTransport {
  /**
   * Send the conversation and stream back the assistant's reply.
   *
   * @param messages  Full conversation so far (including the latest user turn).
   * @param signal    Aborted when the user hits "stop" or the element unmounts.
   */
  send(
    messages: ChatMessage[],
    signal: AbortSignal,
  ): AsyncIterable<StreamChunk>;
}

/**
 * A button your app adds to a message's actions row (next to Copy/Edit). Return
 * them from `messageActions(message)`; pressing one fires `ai-chat:message-action`.
 */
export interface MessageAction {
  /** Your id for it; comes back as `actionId` on the event. */
  readonly id: string;
  /** Accessible name and tooltip — and the visible text when there's no icon. */
  readonly label: string;
  /** Optional SVG markup for an icon button (sanitized; `currentColor` follows the theme). */
  readonly icon?: string;
  /** Shown but not pressable (e.g. while your own work for it is running). */
  readonly disabled?: boolean;
}
